FROM cassandra:3.11

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_URL
ARG VERSION
ARG ARCH
LABEL org.carml.jaeger.agent.build-date=$BUILD_DATE \
      org.carml.jaeger.agent.name="jaeger/cassandra" \
      org.carml.jaeger.agent.description="" \
      org.carml.jaeger.agent.url="https://www.carml.org/" \
      org.carml.jaeger.agent.vcs-ref=$VCS_REF \
      org.carml.jaeger.agent.vcs-url=$VCS_URL \
      org.carml.jaeger.agent.vendor="CarML" \
      org.carml.jaeger.agent.arch=$ARCH \
      org.carml.jaeger.agent.schema-version="1.0"


RUN apt-get update && apt-get install -y --no-install-recommends \
	curl \
	git \
    && \
    rm -rf /var/lib/apt/lists/* 

#Install Go
ENV GIMME_GO_VERSION "1.8.3"
ENV GIMME_OS "linux"
ENV GIMME_ARCH $ARCH

LABEL org.golang.version=$GIMME_GO_VERSION
LABEL org.golang.os=$GIMME_OS
LABEL org.golang.arch=$GIMME_ARCH

ADD https://raw.githubusercontent.com/travis-ci/gimme/master/gimme /usr/bin/gimme
RUN chmod +x /usr/bin/gimme
RUN gimme

ENV GOROOT "/root/.gimme/versions/go${GIMME_GO_VERSION}.${GIMME_OS}.${GIMME_ARCH}"
ENV PATH ${GOROOT}/bin:${PATH}

ENV GOPATH "/go"
ENV PATH $GOPATH/bin:$PATH


#Install Go packages
RUN go get github.com/Masterminds/glide

RUN go get github.com/uber/jaeger && \
    cd $GOPATH/src/github.com/uber/jaeger && \
    glide install && \
    CGO_ENABLED=0 GOOS=linux installsuffix=cgo go build -o ./cmd/agent/agent-linux ./cmd/agent/main.go && \
    cp ./cmd/agent/agent-linux /usr/bin && \
    rm -fr $GOPATH


EXPOSE 5775/udp 6831/udp 6832/udp 5778
CMD ["/usr/bin/agent-linux"]
